In [1]:
from src.args.yaml_config import YamlConfig, YamlConfigModel
from src.models.perch_model import LabelMapping
import pandas as pd

yaml_config = YamlConfig().config

2026-05-05 19:22:31.141103: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
from src.models.perch_model import LabelMapping

label_mapping = LabelMapping(yaml_config)

Number of exact matches: 203
Number of missing mappings: 31

In [3]:
perch_taxonomy = pd.read_csv(yaml_config.base_data_dir + "/perch_taxonomy_labels.csv").rename(columns={"inat2024_fsd50k":"scientific_name"})
birdclef_taxonomy = pd.read_csv(yaml_config.base_data_dir + "/taxonomy.csv")

In [4]:
perch_taxonomy

                scientific_name
0            Abavorana luctuosa
1             Abeillia abeillei
2        Abroscopus albogularis
3        Abroscopus schisticeps
4      Abroscopus superciliaris
...                         ...
14790    Zosterornis whiteheadi
14791           Zulpha perlaria
14792       Zvenella geniculata
14793       Zvenella transversa
14794          Zvenella yunnana

[14795 rows x 1 columns]

In [5]:
birdclef_taxonomy

,primary_label,inat_taxon_id,scientific_name,common_name,class_name
0,1161364,1161364,Guyalna cuta,Guyalna cuta,Insecta
1,116570,116570,Caiman yacare,Southern Spectacled Caiman,Reptilia
2,1176823,1176823,Leptodactylus luctator,Wrestler Frog,Amphibia
3,1491113,1491113,Adenomera guarani,Guaraní leaf-litter frog,Amphibia
4,1595929,1595929,Lysapsus limellum,Uruguay Harlequin Frog,Amphibia
...,...,...,...,...,...
229,yebela1,16714,Elaenia flavogaster,Yellow-bellied Elaenia,Aves
230,yecmac,73272,Primolius auricollis,Golden-collared Macaw,Aves
231,yecpar,19215,Brotogeris chiriri,Yellow-chevroned Parakeet,Aves
232,yehcar1,1432779,Daptrius chimachima,Yellow-headed Caracara,Aves
233,yeofly1,16567,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves

In [6]:
# Calculate exact scientific name matches
exact_matches = set(perch_taxonomy["scientific_name"]).intersection(set(birdclef_taxonomy["scientific_name"]))
print(f"Number of exact matches: {len(exact_matches)}")

Number of exact matches: 203

In [7]:
missing_mappings = set(birdclef_taxonomy["scientific_name"]).difference(set(perch_taxonomy["scientific_name"]))
print(f"Number of missing mappings: {len(missing_mappings)}")

# Write missing mappings to csv
missing_mappings_df = birdclef_taxonomy[birdclef_taxonomy["scientific_name"].isin(missing_mappings)]
missing_mappings_df.to_csv("missing_mappings.csv", index=False)

Number of missing mappings: 31

In [8]:
remaining_perch_taxonomy = perch_taxonomy[~perch_taxonomy["scientific_name"].isin(exact_matches)]

# Write remaining perch taxonomy to csv
remaining_perch_taxonomy.to_csv("remaining_perch_taxonomy.csv", index=False)